// Do not edit. This file is auto-generated.

const cards =
[
null,
{activation:3,symbol:"red-and-blue",special:null,event:"campaign",name:"Campaign"},
{activation:3,symbol:"red-and-blue",special:null,event:"campaign",name:"Campaign"},
{activation:3,symbol:"red-and-blue",special:"reshuffle",event:"campaign",name:"Campaign"},
{activation:3,symbol:"red-and-blue",special:null,event:"campaign",name:"Campaign"},
{activation:1,symbol:"red-and-blue",special:null,event:"bastions_repaired",name:"Bastions Repaired"},
{activation:3,symbol:"red-and-blue",special:"response",event:"surrender",name:"Surrender!"},
{activation:1,symbol:"red-and-blue",special:"response",event:"massacre",name:"Massacre!"},
{activation:1,symbol:"red-and-blue",special:"response",event:"coehorns_and_howitzers",name:"Coehorns & Howitzers"},
{activation:1,symbol:"red-and-blue",special:"response",event:"fieldworks",name:"Fieldworks"},
{activation:1,symbol:"red-and-blue",special:"response",event:"fieldworks",name:"Fieldworks"},
{activation:1,symbol:"red-and-blue",special:"response",event:"ambush",name:"Ambush!"},
{activation:1,symbol:"red-and-blue",special:"response",event:"ambush",name:"Ambush!"},
{activation:1,symbol:"red-and-blue",special:"response",event:"blockhouses",name:"Blockhouses"},
{activation:2,symbol:"red-and-blue",special:"response",event:"foul_weather",name:"Foul Weather"},
{activation:1,symbol:"red-and-blue",special:"response",event:"lake_schooner",name:"Lake Schooner"},
{activation:1,symbol:"red",special:"response",event:"george_croghan",name:"George Croghan"},
{activation:1,symbol:"red",special:"response",event:"amphibious_landing",name:"Amphibious Landing"},
{activation:1,symbol:"red",special:"response",event:"amphibious_landing",name:"Amphibious Landing"},
{activation:1,symbol:"red",special:"response",event:"amphibious_landing",name:"Amphibious Landing"},
{activation:1,symbol:"red",special:"response",event:"amphibious_landing",name:"Amphibious Landing"},
{activation:3,symbol:"blue",special:null,event:"louisbourg_squadrons",name:"Louisbourg Squadrons"},
{activation:3,symbol:"red",special:null,event:"governor_vaudreuil_interferes",name:"Governor Vaudreuil Interferes"},
{activation:2,symbol:"blue",special:null,event:"northern_indian_alliance",name:"Northern Indian Alliance"},
{activation:2,symbol:"blue",special:null,event:"northern_indian_alliance",name:"Northern Indian Alliance"},
{activation:2,symbol:"blue",special:null,event:"northern_indian_alliance",name:"Northern Indian Alliance"},
{activation:2,symbol:"blue",special:null,event:"western_indian_alliance",name:"Western Indian Alliance"},
{activation:2,symbol:"blue",special:null,event:"western_indian_alliance",name:"Western Indian Alliance"},
{activation:3,symbol:"red-and-blue",special:null,event:"iroquois_alliance",name:"Iroquois Alliance"},
{activation:1,symbol:"red",special:null,event:"mohawks",name:"Mohawks"},
{activation:1,symbol:"red",special:null,event:"cherokees",name:"Cherokees"},
{activation:3,symbol:"blue",special:"remove",event:"cherokee_uprising",name:"Cherokee Uprising"},
{activation:2,symbol:"red",special:"remove",event:"treaty_of_easton",name:"Treaty of Easton"},
{activation:2,symbol:"red-and-blue",special:null,event:"indians_desert",name:"Indians Desert"},
{activation:3,symbol:"red-and-blue",special:null,event:"small_pox",name:"Small Pox"},
{activation:3,symbol:"red-and-blue",special:null,event:"courier_intercepted",name:"Courier Intercepted!"},
{activation:2,symbol:"red",special:null,event:"françois_bigot",name:"François Bigot"},
{activation:3,symbol:"blue",special:null,event:"british_ministerial_crisis",name:"British Ministerial Crisis"},
{activation:2,symbol:"blue",special:null,event:"provincial_regiments_dispersed_for_frontier_duty",name:"Provincial Regiments Dispersed for Frontier Duty"},
{activation:2,symbol:"blue",special:null,event:"stingy_provincial_assembly",name:"Stingy Provincial Assembly"},
{activation:2,symbol:"blue",special:null,event:"stingy_provincial_assembly",name:"Stingy Provincial Assembly"},
{activation:3,symbol:"red-and-blue",special:null,event:"british_colonial_politics",name:"British Colonial Politics"},
{activation:3,symbol:"red-and-blue",special:null,event:"british_colonial_politics",name:"British Colonial Politics"},
{activation:2,symbol:"red",special:null,event:"raise_provincial_regiments",name:"Raise Provincial Regiments"},
{activation:2,symbol:"red",special:null,event:"raise_provincial_regiments",name:"Raise Provincial Regiments"},
{activation:2,symbol:"red",special:null,event:"raise_provincial_regiments",name:"Raise Provincial Regiments"},
{activation:2,symbol:"red-and-blue",special:null,event:"colonial_recruits",name:"Colonial Recruits"},
{activation:3,symbol:"red-and-blue",special:null,event:"troop_transports_and_local_enlistments",name:"Troop Transports & Local Enlistments"},
{activation:3,symbol:"red-and-blue",special:null,event:"victories_in_germany_release_troops_and_finances_for_new_world",name:"Victories in Germany Release Troops & Finances for New World"},
{activation:1,symbol:"red-and-blue",special:null,event:"call_out_militias",name:"Call Out Militias"},
{activation:1,symbol:"red-and-blue",special:null,event:"call_out_militias",name:"Call Out Militias"},
{activation:1,symbol:"red-and-blue",special:null,event:"call_out_militias",name:"Call Out Militias"},
{activation:1,symbol:"red-and-blue",special:null,event:"call_out_militias",name:"Call Out Militias"},
{activation:1,symbol:"red",special:null,event:"rangers",name:"Rangers"},
{activation:2,symbol:"red",special:null,event:"light_infantry",name:"Light Infantry"},
{activation:3,symbol:"blue",special:"remove",event:"french_regulars",name:"French Regulars"},
{activation:3,symbol:"blue",special:"remove",event:"french_regulars",name:"French Regulars"},
{activation:3,symbol:"red",special:"remove",event:"british_regulars",name:"British Regulars"},
{activation:3,symbol:"red",special:"remove",event:"british_regulars",name:"British Regulars"},
{activation:3,symbol:"red",special:"remove",event:"british_regulars",name:"British Regulars"},
{activation:3,symbol:"red",special:"remove",event:"highlanders",name:"Highlanders"},
{activation:1,symbol:"red",special:"remove",event:"highlanders",name:"Highlanders"},
{activation:3,symbol:"red",special:"remove",event:"quiberon_bay",name:"Quiberon Bay"},
{activation:1,symbol:"red",special:"remove",event:"highlanders",name:"Highlanders"},
{activation:3,symbol:"red",special:"remove",event:"british_regulars",name:"British Regulars"},
{activation:3,symbol:"red",special:"remove",event:"royal_americans",name:"Royal Americans"},
{activation:2,symbol:"red-and-blue",special:"remove",event:"acadians_expelled",name:"Acadians Expelled"},
{activation:3,symbol:"red",special:"remove",event:"william_pitt",name:"William Pitt"},
{activation:3,symbol:"blue",special:"remove",event:"french_regulars",name:"French Regulars"},
{activation:3,symbol:"blue",special:"remove",event:"diplomatic_revolution",name:"Diplomatic Revolution"},
{activation:2,symbol:"blue",special:"remove",event:"intrigues_against_shirley",name:"Intrigues Against Shirley"}
]

const pieces =
[
{name:"None"},
{faction:"british",type:"leader",name:"Amherst",initiative:2,command:7,tactics:1,movement:6,desc:"2-7-1 Amherst",square:"british_square_leader_seven m2s",tall:"british_leader_seven t2s"},
{faction:"british",type:"leader",name:"Braddock",initiative:2,command:7,tactics:0,movement:6,desc:"2-7-0 Braddock",square:"british_square_leader_seven m3s",tall:"british_leader_seven t3s"},
{faction:"british",type:"leader",name:"Abercromby",initiative:3,command:7,tactics:0,movement:6,desc:"3-7-0 Abercromby",square:"british_square_leader_seven m1s",tall:"british_leader_seven t1s"},
{faction:"british",type:"leader",name:"Loudoun",initiative:3,command:7,tactics:0,movement:6,desc:"3-7-0 Loudoun",square:"british_square_leader_seven m4s",tall:"british_leader_seven t4s"},
{faction:"british",type:"leader",name:"Wolfe",initiative:1,command:6,tactics:2,movement:6,desc:"1-6-2 Wolfe",square:"british_square_leader m9s",tall:"british_leader t9s"},
{faction:"british",type:"leader",name:"Forbes",initiative:1,command:6,tactics:0,movement:6,desc:"1-6-0 Forbes",square:"british_square_leader m3s",tall:"british_leader t3s"},
{faction:"british",type:"leader",name:"Shirley",initiative:2,command:6,tactics:0,movement:6,desc:"2-6-0 Shirley",square:"british_square_leader m7s",tall:"british_leader t7s"},
{faction:"british",type:"leader",name:"Murray",initiative:1,command:5,tactics:0,movement:6,desc:"1-5-0 Murray",square:"british_square_leader m6s",tall:"british_leader t6s"},
{faction:"british",type:"leader",name:"Monckton",initiative:2,command:5,tactics:0,movement:6,desc:"2-5-0 Monckton",square:"british_square_leader m5s",tall:"british_leader t5s"},
{faction:"british",type:"leader",name:"Webb",initiative:3,command:5,tactics:0,movement:6,desc:"3-5-0 Webb",square:"british_square_leader m8s",tall:"british_leader t8s"},
{faction:"british",type:"leader",name:"Bradstreet",initiative:1,command:4,tactics:1,movement:6,desc:"1-4-1 Bradstreet",square:"british_square_leader m1s",tall:"british_leader t1s"},
{faction:"british",type:"leader",name:"Dunbar",initiative:3,command:4,tactics:0,movement:6,desc:"3-4-0 Dunbar",square:"british_square_leader m2s",tall:"british_leader t2s"},
{faction:"british",type:"leader",name:"Johnson",initiative:1,command:3,tactics:1,movement:6,desc:"1-3-1 Johnson",square:"british_square_leader m4s",tall:"british_leader t4s"},
{faction:"british",type:"indian",subtype:"cherokee",name:"Cherokee",strength:1,reduced_strength:0,movement:6,desc:"1-6 Cherokee",rdesc:"0-6 Cherokee",counter:"british_indian_cherokee c1"},
{faction:"british",type:"indian",subtype:"cherokee",name:"Cherokee",strength:1,reduced_strength:0,movement:6,desc:"1-6 Cherokee",rdesc:"0-6 Cherokee",counter:"british_indian_cherokee c1"},
{faction:"british",type:"indian",subtype:"gray",name:"Cayuga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Cayuga",rdesc:"0-6 Cayuga",counter:"british_indian_gray c1"},
{faction:"british",type:"indian",subtype:"gray",name:"Oneida",strength:1,reduced_strength:0,movement:6,desc:"1-6 Oneida",rdesc:"0-6 Oneida",counter:"british_indian_gray c2"},
{faction:"british",type:"indian",subtype:"gray",name:"Onondaga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Onondaga",rdesc:"0-6 Onondaga",counter:"british_indian_gray c3"},
{faction:"british",type:"indian",subtype:"gray",name:"Seneca",strength:1,reduced_strength:0,movement:6,desc:"1-6 Seneca",rdesc:"0-6 Seneca",counter:"british_indian_gray c4"},
{faction:"british",type:"indian",subtype:"gray",name:"Tuscarora",strength:1,reduced_strength:0,movement:6,desc:"1-6 Tuscarora",rdesc:"0-6 Tuscarora",counter:"british_indian_gray c5"},
{faction:"british",type:"indian",subtype:"mohawk",name:"Mohawk",strength:1,reduced_strength:0,movement:6,desc:"1-6 Mohawk",rdesc:"0-6 Mohawk",counter:"british_indian_mohawk c1"},
{faction:"british",type:"indian",subtype:"mohawk",name:"Mohawk",strength:1,reduced_strength:0,movement:6,desc:"1-6 Mohawk",rdesc:"0-6 Mohawk",counter:"british_indian_mohawk c1"},
{faction:"british",type:"ranger",name:"Armstrong",strength:2,reduced_strength:1,movement:6,desc:"2-6 ranger",rdesc:"1-6 ranger",counter:"british_ranger c1"},
{faction:"british",type:"ranger",name:"Goreham",strength:2,reduced_strength:1,movement:6,desc:"2-6 ranger",rdesc:"1-6 ranger",counter:"british_ranger c2"},
{faction:"british",type:"ranger",name:"Rogers",strength:2,reduced_strength:1,movement:6,desc:"2-6 ranger",rdesc:"1-6 ranger",counter:"british_ranger c3"},
{faction:"british",type:"light infantry",name:"1/95th",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m1"},
{faction:"british",type:"light infantry",name:"2/95th",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m2"},
{faction:"british",type:"light infantry",name:"85th Ryl. Vol.",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m3"},
{faction:"british",type:"light infantry",name:"Gage's 80th",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m4"},
{faction:"british",type:"light infantry",name:"Howe's",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m5"},
{faction:"british",type:"light infantry",name:"Scott's",strength:2,reduced_strength:1,movement:6,desc:"2-6 light infantry",rdesc:"1-6 light infantry",counter:"british_light_infantry m6"},
{faction:"british",type:"northern provincial",name:"Connecticut",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m1"},
{faction:"british",type:"northern provincial",name:"Connecticut",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m1"},
{faction:"british",type:"northern provincial",name:"Connecticut",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m1"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"Massachusetts",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m2"},
{faction:"british",type:"northern provincial",name:"New Hampshire",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m3"},
{faction:"british",type:"northern provincial",name:"New Jersey",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m4"},
{faction:"british",type:"northern provincial",name:"New Jersey",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m4"},
{faction:"british",type:"northern provincial",name:"New York",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m5"},
{faction:"british",type:"northern provincial",name:"New York",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m5"},
{faction:"british",type:"northern provincial",name:"New York",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m5"},
{faction:"british",type:"northern provincial",name:"New York",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m5"},
{faction:"british",type:"northern provincial",name:"New York",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m5"},
{faction:"british",type:"northern provincial",name:"Rhode Island",strength:2,reduced_strength:1,movement:4,desc:"2-4 northern provincial",rdesc:"1-4 northern provincial",counter:"british_northern_provincial m6"},
{faction:"british",type:"southern provincial",name:"Maryland",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m1"},
{faction:"british",type:"southern provincial",name:"Pennsylvania",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m2"},
{faction:"british",type:"southern provincial",name:"Pennsylvania",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m2"},
{faction:"british",type:"southern provincial",name:"Pennsylvania",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m2"},
{faction:"british",type:"southern provincial",name:"Virginia",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m3"},
{faction:"british",type:"southern provincial",name:"Virginia",strength:2,reduced_strength:1,movement:4,desc:"2-4 southern provincial",rdesc:"1-4 southern provincial",counter:"british_southern_provincial m3"},
{faction:"british",type:"regular",name:"15th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m1"},
{faction:"british",type:"regular",name:"17th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m2"},
{faction:"british",type:"regular",name:"1st Royal",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m3"},
{faction:"british",type:"regular",name:"22nd",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m4"},
{faction:"british",type:"regular",name:"27th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m5"},
{faction:"british",type:"regular",name:"28th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m6"},
{faction:"british",type:"regular",name:"35th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m7"},
{faction:"british",type:"regular",name:"40th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m8"},
{faction:"british",type:"regular",name:"43rd",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m9"},
{faction:"british",type:"regular",name:"44th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m10"},
{faction:"british",type:"regular",name:"45th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m11"},
{faction:"british",type:"regular",name:"46th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m12"},
{faction:"british",type:"regular",name:"47th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m13"},
{faction:"british",type:"regular",name:"48th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m14"},
{faction:"british",type:"regular",name:"55th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m15"},
{faction:"british",type:"regular",name:"58th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m16"},
{faction:"british",type:"regular",name:"90th",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"british_regular m17"},
{faction:"british",type:"royal american",name:"1/60th",strength:4,reduced_strength:3,movement:4,desc:"4-4 royal american",rdesc:"3-4 royal american",counter:"british_royal_american m1"},
{faction:"british",type:"royal american",name:"2/60th",strength:4,reduced_strength:3,movement:4,desc:"4-4 royal american",rdesc:"3-4 royal american",counter:"british_royal_american m2"},
{faction:"british",type:"royal american",name:"3/60th",strength:4,reduced_strength:3,movement:4,desc:"4-4 royal american",rdesc:"3-4 royal american",counter:"british_royal_american m3"},
{faction:"british",type:"royal american",name:"4/60th",strength:4,reduced_strength:3,movement:4,desc:"4-4 royal american",rdesc:"3-4 royal american",counter:"british_royal_american m4"},
{faction:"british",type:"highland",name:"1/42nd",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m1"},
{faction:"british",type:"highland",name:"2/42nd",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m2"},
{faction:"british",type:"highland",name:"77th (a)",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m3"},
{faction:"british",type:"highland",name:"77th (b)",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m4"},
{faction:"british",type:"highland",name:"78th (a)",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m5"},
{faction:"british",type:"highland",name:"78th (b)",strength:4,reduced_strength:3,movement:4,desc:"4-4 highland",rdesc:"3-4 highland",counter:"british_highland m6"},
{faction:"british",type:"militia",name:"Colonial Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"british_militia m1"},
{faction:"british",type:"militia",name:"Colonial Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"british_militia m1"},
{faction:"british",type:"militia",name:"Colonial Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"british_militia m1"},
{faction:"british",type:"militia",name:"Colonial Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"british_militia m1"},
{faction:"french",type:"leader",name:"Montcalm",initiative:1,command:6,tactics:2,movement:6,desc:"1-6-2 Montcalm",square:"french_square_leader m7s",tall:"french_leader t7s"},
{faction:"french",type:"leader",name:"Dieskau",initiative:2,command:6,tactics:0,movement:6,desc:"2-6-0 Dieskau",square:"french_square_leader m3s",tall:"french_leader t3s"},
{faction:"french",type:"leader",name:"Lévis",initiative:2,command:5,tactics:1,movement:6,desc:"2-5-1 Lévis",square:"french_square_leader m6s",tall:"french_leader t6s"},
{faction:"french",type:"leader",name:"Vaudreuil",initiative:3,command:5,tactics:0,movement:6,desc:"3-5-0 Vaudreuil",square:"french_square_leader m9s",tall:"french_leader t9s"},
{faction:"french",type:"leader",name:"Drucour",initiative:2,command:4,tactics:1,movement:6,desc:"2-4-1 Drucour",square:"french_square_leader m4s",tall:"french_leader t4s"},
{faction:"french",type:"leader",name:"Rigaud",initiative:2,command:4,tactics:0,movement:6,desc:"2-4-0 Rigaud",square:"french_square_leader m8s",tall:"french_leader t8s"},
{faction:"french",type:"leader",name:"Villiers",initiative:2,command:3,tactics:1,movement:6,desc:"2-3-1 Villiers",square:"french_square_leader m10s",tall:"french_leader t10s"},
{faction:"french",type:"leader",name:"Bougainville",initiative:1,command:3,tactics:0,movement:6,desc:"1-3-0 Bougainville",square:"french_square_leader m2s",tall:"french_leader t2s"},
{faction:"french",type:"leader",name:"Beaujeu",initiative:1,command:2,tactics:1,movement:6,desc:"1-2-1 Beaujeu",square:"french_square_leader m1s",tall:"french_leader t1s"},
{faction:"french",type:"leader",name:"Dumas",initiative:1,command:2,tactics:1,movement:6,desc:"1-2-1 Dumas",square:"french_square_leader m5s",tall:"french_leader t5s"},
{faction:"french",type:"indian",subtype:"blue-orange",name:"Huron",strength:1,reduced_strength:0,movement:6,desc:"1-6 Huron",rdesc:"0-6 Huron",counter:"french_indian_blue_orange c1"},
{faction:"french",type:"indian",subtype:"blue-orange",name:"Ojibwa",strength:1,reduced_strength:0,movement:6,desc:"1-6 Ojibwa",rdesc:"0-6 Ojibwa",counter:"french_indian_blue_orange c2"},
{faction:"french",type:"indian",subtype:"blue-orange",name:"Ottawa",strength:1,reduced_strength:0,movement:6,desc:"1-6 Ottawa",rdesc:"0-6 Ottawa",counter:"french_indian_blue_orange c3"},
{faction:"french",type:"indian",subtype:"blue-orange",name:"Potawatomi",strength:1,reduced_strength:0,movement:6,desc:"1-6 Potawatomi",rdesc:"0-6 Potawatomi",counter:"french_indian_blue_orange c4"},
{faction:"french",type:"indian",subtype:"blue",name:"Abenaki",strength:1,reduced_strength:0,movement:6,desc:"1-6 Abenaki",rdesc:"0-6 Abenaki",counter:"french_indian_blue c1"},
{faction:"french",type:"indian",subtype:"blue",name:"Abenaki",strength:1,reduced_strength:0,movement:6,desc:"1-6 Abenaki",rdesc:"0-6 Abenaki",counter:"french_indian_blue c2"},
{faction:"french",type:"indian",subtype:"blue",name:"Algonquin",strength:1,reduced_strength:0,movement:6,desc:"1-6 Algonquin",rdesc:"0-6 Algonquin",counter:"french_indian_blue c3"},
{faction:"french",type:"indian",subtype:"blue",name:"Algonquin",strength:1,reduced_strength:0,movement:6,desc:"1-6 Algonquin",rdesc:"0-6 Algonquin",counter:"french_indian_blue c4"},
{faction:"french",type:"indian",subtype:"blue",name:"Caughnawaga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Caughnawaga",rdesc:"0-6 Caughnawaga",counter:"french_indian_blue c5"},
{faction:"french",type:"indian",subtype:"blue",name:"Caughnawaga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Caughnawaga",rdesc:"0-6 Caughnawaga",counter:"french_indian_blue c6"},
{faction:"french",type:"indian",subtype:"blue",name:"Mississauga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Mississauga",rdesc:"0-6 Mississauga",counter:"french_indian_blue c7"},
{faction:"french",type:"indian",subtype:"gray",name:"Cayuga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Cayuga",rdesc:"0-6 Cayuga",counter:"french_indian_gray c1"},
{faction:"french",type:"indian",subtype:"gray",name:"Oneida",strength:1,reduced_strength:0,movement:6,desc:"1-6 Oneida",rdesc:"0-6 Oneida",counter:"french_indian_gray c2"},
{faction:"french",type:"indian",subtype:"gray",name:"Onondaga",strength:1,reduced_strength:0,movement:6,desc:"1-6 Onondaga",rdesc:"0-6 Onondaga",counter:"french_indian_gray c3"},
{faction:"french",type:"indian",subtype:"gray",name:"Seneca",strength:1,reduced_strength:0,movement:6,desc:"1-6 Seneca",rdesc:"0-6 Seneca",counter:"french_indian_gray c4"},
{faction:"french",type:"indian",subtype:"gray",name:"Tuscarora",strength:1,reduced_strength:0,movement:6,desc:"1-6 Tuscarora",rdesc:"0-6 Tuscarora",counter:"french_indian_gray c5"},
{faction:"french",type:"indian",subtype:"orange",name:"Delaware",strength:1,reduced_strength:0,movement:6,desc:"1-6 Delaware",rdesc:"0-6 Delaware",counter:"french_indian_orange c1"},
{faction:"french",type:"indian",subtype:"orange",name:"Delaware",strength:1,reduced_strength:0,movement:6,desc:"1-6 Delaware",rdesc:"0-6 Delaware",counter:"french_indian_orange c2"},
{faction:"french",type:"indian",subtype:"orange",name:"Mingo",strength:1,reduced_strength:0,movement:6,desc:"1-6 Mingo",rdesc:"0-6 Mingo",counter:"french_indian_orange c3"},
{faction:"french",type:"indian",subtype:"orange",name:"Mingo",strength:1,reduced_strength:0,movement:6,desc:"1-6 Mingo",rdesc:"0-6 Mingo",counter:"french_indian_orange c4"},
{faction:"french",type:"indian",subtype:"orange",name:"Shawnee",strength:1,reduced_strength:0,movement:6,desc:"1-6 Shawnee",rdesc:"0-6 Shawnee",counter:"french_indian_orange c5"},
{faction:"french",type:"indian",subtype:"orange",name:"Shawnee",strength:1,reduced_strength:0,movement:6,desc:"1-6 Shawnee",rdesc:"0-6 Shawnee",counter:"french_indian_orange c6"},
{faction:"french",type:"coureurs",name:"Boishébert Acadian",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c1"},
{faction:"french",type:"coureurs",name:"Joncaire",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c2"},
{faction:"french",type:"coureurs",name:"Langlade",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c3"},
{faction:"french",type:"coureurs",name:"Ligneris",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c4"},
{faction:"french",type:"coureurs",name:"Léry",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c5"},
{faction:"french",type:"coureurs",name:"Marin",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c6"},
{faction:"french",type:"coureurs",name:"Perière",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c7"},
{faction:"french",type:"coureurs",name:"Repentigny",strength:1,reduced_strength:0,movement:6,desc:"1-6 coureurs",rdesc:"0-6 coureurs",counter:"french_coureurs c8"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"marine detachment",name:"Marine Detachment",strength:1,reduced_strength:0,movement:4,desc:"1-4 marine detachment",rdesc:"0-4 marine detachment",counter:"french_marine_detachment m1"},
{faction:"french",type:"regular",name:"2/Berry",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m1"},
{faction:"french",type:"regular",name:"3/Berry",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m2"},
{faction:"french",type:"regular",name:"Artois",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m3"},
{faction:"french",type:"regular",name:"Bourgogne",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m4"},
{faction:"french",type:"regular",name:"Béarn",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m5"},
{faction:"french",type:"regular",name:"Cambis",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m6"},
{faction:"french",type:"regular",name:"Guyenne",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m7"},
{faction:"french",type:"regular",name:"La Reine",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m8"},
{faction:"french",type:"regular",name:"La Sarre",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m9"},
{faction:"french",type:"regular",name:"Languedoc",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m10"},
{faction:"french",type:"regular",name:"Marine",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m11"},
{faction:"french",type:"regular",name:"Marine",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m11"},
{faction:"french",type:"regular",name:"Royal Roussillon",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m12"},
{faction:"french",type:"regular",name:"V. Étrangers",strength:3,reduced_strength:2,movement:4,desc:"3-4 regular",rdesc:"2-4 regular",counter:"french_regular m13"},
{faction:"french",type:"militia",name:"Canadian Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"french_militia m1"},
{faction:"french",type:"militia",name:"Canadian Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"french_militia m1"},
{faction:"french",type:"militia",name:"Canadian Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"french_militia m1"},
{faction:"french",type:"militia",name:"Canadian Militia",strength:1,reduced_strength:1,movement:0,desc:"1-0 militia",rdesc:"1-0 militia",counter:"french_militia m1"}
]

const spaces =
[
{name:"none"},
{type:"cultivated",name:"Boston",department:"northern",x:1857,y:1080,w:118,h:104,land:[18,21,9,13],river:[],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"New Haven",department:"northern",x:1444,y:1179,w:66,h:66,land:[3,15,10],river:[],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"New York",department:"northern",x:1270,y:1239,w:115,h:117,land:[20,5,2],river:[15],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"Albany",department:"northern",x:1416,y:859,w:87,h:118,land:[100,11],river:[73,12,19],lakeshore:[],is_fortress:true},
{type:"cultivated",name:"Burlington",department:"northern",x:1151,y:1325,w:66,h:66,land:[3],river:[20,24],lakeshore:[]},
{type:"cultivated",name:"Charlestown",department:"northern",x:1697,y:839,w:66,h:66,land:[128,138],river:[114,8],lakeshore:[]},
{type:"cultivated",name:"Concord",department:"northern",x:1929,y:840,w:66,h:66,land:[16,94,136,138],river:[13],lakeshore:[]},
{type:"cultivated",name:"Deerfield",department:"northern",x:1650,y:971,w:66,h:66,land:[21,138,128],river:[6,14],lakeshore:[]},
{type:"cultivated",name:"Gloucester",department:"northern",x:1934,y:1007,w:66,h:66,land:[1,16],river:[13],lakeshore:[]},
{type:"cultivated",name:"Hartford",department:"northern",x:1564,y:1123,w:66,h:66,land:[2,17,18],river:[14],lakeshore:[]},
{type:"cultivated",name:"Hoosic",department:"northern",x:1551,y:942,w:66,h:66,land:[128,14,4,73],river:[],lakeshore:[]},
{type:"cultivated",name:"Kinderhook",department:"northern",x:1374,y:991,w:101,h:65,land:[129,14],river:[4,17],lakeshore:[]},
{type:"cultivated",name:"Manchester",department:"northern",x:1851,y:911,w:66,h:66,land:[138,16,1,21],river:[9,7],lakeshore:[]},
{type:"cultivated",name:"Northampton",department:"northern",x:1579,y:1036,w:66,h:66,land:[21,11,12],river:[8,10],lakeshore:[]},
{type:"cultivated",name:"Peekskill",department:"northern",x:1287,y:1154,w:101,h:65,land:[129,2],river:[17,3],lakeshore:[]},
{type:"cultivated",name:"Portsmouth",department:"northern",x:1991,y:931,w:66,h:66,land:[9,57,7,13],river:[],lakeshore:[]},
{type:"cultivated",name:"Poughkeepsie",department:"northern",x:1336,y:1077,w:101,h:65,land:[129,10],river:[12,15],lakeshore:[]},
{type:"cultivated",name:"Providence",department:"northern",x:1765,y:1179,w:66,h:66,land:[10,1,21],river:[],lakeshore:[]},
{type:"cultivated",name:"Schenectady",department:"northern",x:1351,y:787,w:66,h:66,land:[122,100],river:[56,4],lakeshore:[]},
{type:"cultivated",name:"Trenton",department:"northern",x:1123,y:1237,w:66,h:66,land:[35,3],river:[29,5],lakeshore:[]},
{type:"cultivated",name:"Worcester",department:"northern",x:1750,y:1058,w:66,h:66,land:[1,18,13,14,8],river:[],lakeshore:[]},
{type:"cultivated",name:"Alexandria",department:"southern",x:631,y:1436,w:87,h:87,land:[25,23],river:[30],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"Baltimore",department:"southern",x:758,y:1374,w:88,h:87,land:[22,32,30],river:[],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"Philadelphia",department:"southern",x:1040,y:1316,w:88,h:88,land:[35],river:[5,34],lakeshore:[],is_fortress:true,is_port:true},
{type:"cultivated",name:"Ashby's Gap",department:"southern",x:535,y:1394,w:66,h:66,land:[28,22,30,38,37],river:[],lakeshore:[]},
{type:"cultivated",name:"Augusta",department:"southern",x:357,y:1445,w:66,h:66,land:[125,28,38],river:[],lakeshore:[]},
{type:"cultivated",name:"Carlisle",department:"southern",x:671,y:1171,w:66,h:66,land:[40,99,36],river:[31],lakeshore:[]},
{type:"cultivated",name:"Culpeper",department:"southern",x:471,y:1481,w:66,h:66,land:[26,25,38],river:[],lakeshore:[]},
{type:"cultivated",name:"Easton",department:"southern",x:1106,y:1125,w:66,h:66,land:[135,35],river:[65,20],lakeshore:[]},
{type:"cultivated",name:"Frederick",department:"southern",x:641,y:1328,w:66,h:66,land:[40,23,25],river:[36,22],lakeshore:[]},
{type:"cultivated",name:"Harris's Ferry",department:"southern",x:793,y:1119,w:66,h:66,land:[],river:[33,27,75,39,101],lakeshore:[]},
{type:"cultivated",name:"Head of Elk",department:"southern",x:867,y:1336,w:66,h:66,land:[23,34,33],river:[39],lakeshore:[]},
{type:"cultivated",name:"Lancaster",department:"southern",x:933,y:1181,w:66,h:66,land:[34,32,39,135,35],river:[31],lakeshore:[]},
{type:"cultivated",name:"New Castle",department:"southern",x:964,y:1367,w:66,h:66,land:[32,33],river:[24],lakeshore:[]},
{type:"cultivated",name:"Reading",department:"southern",x:1028,y:1204,w:66,h:66,land:[135,33,20,24,29],river:[],lakeshore:[]},
{type:"cultivated",name:"Shepherd's Ferry",department:"southern",x:586,y:1231,w:66,h:66,land:[40,37,27],river:[115,30],lakeshore:[]},
{type:"cultivated",name:"Winchester",department:"southern",x:503,y:1291,w:66,h:66,land:[25,125,38,115,36],river:[],lakeshore:[]},
{type:"cultivated",name:"Woodstock",department:"southern",x:432,y:1370,w:66,h:66,land:[25,28,26,37,125],river:[],lakeshore:[]},
{type:"cultivated",name:"Wright's Ferry",department:"southern",x:849,y:1239,w:66,h:66,land:[33,40],river:[31,32],lakeshore:[]},
{type:"cultivated",name:"York",department:"southern",x:752,y:1242,w:66,h:66,land:[39,30,27,36],river:[],lakeshore:[]},
{type:"cultivated",name:"Québec",department:"st_lawrence",x:2104,y:130,w:88,h:134,land:[134],river:[44],lakeshore:[52],is_fortress:true,is_port:true},
{type:"cultivated",name:"Montréal",department:"st_lawrence",x:1606,y:267,w:118,h:118,land:[119,50],river:[48,46,45],lakeshore:[],is_fortress:true},
{type:"cultivated",name:"Baie-St-Paul",department:"st_lawrence",x:2290,y:104,w:68,h:68,land:[],river:[],lakeshore:[52]},
{type:"cultivated",name:"Bécancour",department:"st_lawrence",x:2020,y:202,w:66,h:66,land:[49,134],river:[41,51],lakeshore:[]},
{type:"cultivated",name:"Kahnawake",department:"st_lawrence",x:1519,y:354,w:68,h:68,land:[46],river:[42,103],lakeshore:[]},
{type:"cultivated",name:"Lac des Deux Montagnes",department:"st_lawrence",x:1482,y:238,w:68,h:68,land:[45],river:[42],lakeshore:[]},
{type:"cultivated",name:"Rivière-Ouelle",department:"st_lawrence",x:2297,y:196,w:68,h:68,land:[],river:[],lakeshore:[52]},
{type:"cultivated",name:"Sorel",department:"st_lawrence",x:1804,y:225,w:66,h:66,land:[],river:[51,42,49,50],lakeshore:[]},
{type:"cultivated",name:"St-François",department:"st_lawrence",x:1896,y:297,w:66,h:66,land:[134,82,51,44],river:[48],lakeshore:[]},
{type:"cultivated",name:"St-Jean",department:"st_lawrence",x:1771,y:342,w:66,h:66,land:[42,82],river:[48,119],lakeshore:[]},
{type:"cultivated",name:"Trois-Rivières",department:"st_lawrence",x:1908,y:194,w:66,h:66,land:[49],river:[44,48],lakeshore:[]},
{type:"cultivated",name:"Île d'Orléans",department:"st_lawrence",x:2209,y:174,w:68,h:68,land:[],river:[],lakeshore:[41,47,43]},
{type:"wilderness",name:"Ammonoosuc",x:1925,y:549,w:74,h:74,land:[137,133,127],river:[63],lakeshore:[]},
{type:"wilderness",name:"Black River",x:1218,y:490,w:74,h:74,land:[112,87,95,120],river:[],lakeshore:[]},
{type:"wilderness",name:"Buffalo Swamp",x:508,y:893,w:74,h:74,land:[77,123,78],river:[],lakeshore:[]},
{type:"wilderness",name:"Canajoharie",x:1255,y:753,w:76,h:76,land:[102,91,100,122],river:[89,19],lakeshore:[]},
{type:"wilderness",name:"Casco Bay",x:2066,y:851,w:74,h:74,land:[16,137,94],river:[],lakeshore:[]},
{type:"wilderness",name:"Cataraqui",x:1121,y:390,w:100,h:100,land:[],river:[95],lakeshore:[70,87]},
{type:"wilderness",name:"Cattaraugus Creek",x:513,y:625,w:74,h:74,land:[109],river:[],lakeshore:[79,97]},
{type:"wilderness",name:"Cayuga",x:894,y:799,w:76,h:76,land:[92,69,76,93,107,132],river:[],lakeshore:[]},
{type:"wilderness",name:"Chenussio",x:754,y:608,w:74,h:74,land:[76,80,79,69,74],river:[],lakeshore:[]},
{type:"wilderness",name:"Chinklacamoose",x:724,y:878,w:74,h:74,land:[124,123,113],river:[],lakeshore:[]},
{type:"wilderness",name:"Cowass",x:1853,y:635,w:74,h:74,land:[136,137,127,126],river:[53,114],lakeshore:[]},
{type:"wilderness",name:"Crown Point",x:1580,y:591,w:74,h:74,land:[121,126],river:[],lakeshore:[106,116]},
{type:"wilderness",name:"East Delaware",x:1198,y:1088,w:74,h:74,land:[129],river:[104,29],lakeshore:[]},
{type:"wilderness",name:"East Susquehanna",x:938,y:1034,w:74,h:74,land:[135,132],river:[101,118],lakeshore:[]},
{type:"wilderness",name:"French Creek",x:318,y:719,w:74,h:74,land:[78,97],river:[111],lakeshore:[]},
{type:"wilderness",name:"Ganaraske",x:764,y:368,w:74,h:74,land:[],river:[],lakeshore:[108,98]},
{type:"wilderness",name:"Gannagaro",x:892,y:681,w:74,h:74,land:[61,76,74,92,60],river:[],lakeshore:[]},
{type:"wilderness",name:"Ganneious",x:1012,y:420,w:74,h:74,land:[],river:[],lakeshore:[98,58]},
{type:"wilderness",name:"Gist's Station",x:378,y:1066,w:74,h:74,land:[131,88,110,130],river:[],lakeshore:[]},
{type:"wilderness",name:"Hudson Carry North",x:1456,y:735,w:74,h:74,land:[120,122,73],river:[],lakeshore:[106]},
{type:"wilderness",name:"Hudson Carry South",x:1512,y:802,w:74,h:74,land:[11,128,117,72],river:[4],lakeshore:[]},
{type:"wilderness",name:"Irondequoit",x:869,y:555,w:74,h:74,land:[69,61],river:[],lakeshore:[96,105]},
{type:"wilderness",name:"Juniata",x:728,y:1036,w:74,h:74,land:[123,99],river:[31],lakeshore:[]},
{type:"wilderness",name:"Karaghiyadirha",x:799,y:728,w:76,h:76,land:[124,80,61,69,60],river:[],lakeshore:[]},
{type:"wilderness",name:"Kittaning",x:391,y:916,w:76,h:76,land:[130,55],river:[111,88],lakeshore:[]},
{type:"wilderness",name:"La Belle River",x:469,y:784,w:74,h:74,land:[55,111,67,109],river:[],lakeshore:[]},
{type:"wilderness",name:"La Belle-Famille",x:633,y:572,w:74,h:74,land:[61],river:[86],lakeshore:[59]},
{type:"wilderness",name:"Little Seneca River",x:660,y:691,w:74,h:74,land:[109,124,76,61],river:[],lakeshore:[]},
{type:"wilderness",name:"Logstown",x:225,y:904,w:76,h:76,land:[],river:[88,83],lakeshore:[]},
{type:"wilderness",name:"Memphremagog",x:1889,y:405,w:74,h:74,land:[50,127,133,49],river:[],lakeshore:[]},
{type:"wilderness",name:"Mingo Town",x:172,y:1008,w:76,h:76,land:[110],river:[81],lakeshore:[]},
{type:"wilderness",name:"Mississauga",x:519,y:383,w:76,h:76,land:[],river:[],lakeshore:[108,86]},
{type:"wilderness",name:"Mohawks Branch",x:1119,y:903,w:74,h:74,land:[104,93,102,100,129],river:[],lakeshore:[]},
{type:"wilderness",name:"Niagara",x:609,y:447,w:100,h:100,land:[],river:[79],lakeshore:[105,84]},
{type:"wilderness",name:"Niaouré Bay",x:1119,y:533,w:74,h:74,land:[54],river:[],lakeshore:[58,96]},
{type:"wilderness",name:"Ohio Forks",x:286,y:973,w:100,h:100,land:[71,110,130],river:[77,81],lakeshore:[]},
{type:"wilderness",name:"Oneida Carry East",x:1215,y:679,w:74,h:74,land:[91,90,112,122],river:[56],lakeshore:[]},
{type:"wilderness",name:"Oneida Carry West",x:1126,y:631,w:74,h:74,land:[92,91,89,112],river:[96],lakeshore:[]},
{type:"wilderness",name:"Oneida Castle",x:1130,y:730,w:76,h:76,land:[92,90,93,102,56,89],river:[],lakeshore:[]},
{type:"wilderness",name:"Onondaga",x:1033,y:687,w:76,h:76,land:[91,69,96,90,60,93],river:[],lakeshore:[]},
{type:"wilderness",name:"Osewingo",x:1037,y:801,w:74,h:74,land:[60,107,92,91,85],river:[],lakeshore:[]},
{type:"wilderness",name:"Ossipee",x:2000,y:731,w:74,h:74,land:[137,57,7,136],river:[],lakeshore:[]},
{type:"wilderness",name:"Oswegatchie",x:1267,y:375,w:74,h:74,land:[54],river:[103,58],lakeshore:[]},
{type:"wilderness",name:"Oswego",x:986,y:559,w:100,h:100,land:[92],river:[90],lakeshore:[87,74]},
{type:"wilderness",name:"Presqu'île",x:386,y:638,w:74,h:74,land:[67],river:[],lakeshore:[59]},
{type:"wilderness",name:"Quinte",x:898,y:401,w:74,h:74,land:[],river:[],lakeshore:[68,70]},
{type:"wilderness",name:"Raystown",x:607,y:1081,w:74,h:74,land:[27,115,130,123,75],river:[],lakeshore:[]},
{type:"wilderness",name:"Schoharie",x:1293,y:865,w:74,h:74,land:[19,4,129,85,56],river:[],lakeshore:[]},
{type:"wilderness",name:"Shamokin",x:853,y:1040,w:74,h:74,land:[135],river:[31,113,66],lakeshore:[]},
{type:"wilderness",name:"Shawiangto",x:1176,y:826,w:76,h:76,land:[91,56,85],river:[],lakeshore:[]},
{type:"wilderness",name:"St-Régis",x:1399,y:346,w:74,h:74,land:[121],river:[45,95],lakeshore:[]},
{type:"wilderness",name:"Station Point",x:1140,y:1001,w:74,h:74,land:[129,118,85],river:[65],lakeshore:[]},
{type:"wilderness",name:"Tegynagerunte",x:754,y:489,w:74,h:74,land:[],river:[],lakeshore:[74,86]},
{type:"wilderness",name:"Ticonderoga",x:1550,y:679,w:74,h:74,land:[120,117,126],river:[],lakeshore:[72,64]},
{type:"wilderness",name:"Tioga",x:1009,y:906,w:74,h:74,land:[93,60,132,118],river:[],lakeshore:[]},
{type:"wilderness",name:"Toronto",x:633,y:345,w:74,h:74,land:[],river:[],lakeshore:[84,68]},
{type:"wilderness",name:"Upper La Belle River",x:557,y:738,w:74,h:74,land:[78,59,80,124],river:[],lakeshore:[]},
{type:"wilderness",name:"Upper Monongahela",x:234,y:1107,w:74,h:74,land:[83,125,88,71,131],river:[],lakeshore:[]},
{type:"wilderness",name:"Venango",x:357,y:820,w:74,h:74,land:[78],river:[67,77],lakeshore:[]},
{type:"wilderness",name:"West Canada Creek",x:1274,y:574,w:74,h:74,land:[90,89,54,120],river:[],lakeshore:[]},
{type:"wilderness",name:"West Susquehanna",x:797,y:945,w:74,h:74,land:[62,132],river:[101],lakeshore:[]},
{type:"wilderness",name:"White River Falls",x:1760,y:729,w:74,h:74,land:[126,136],river:[63,6],lakeshore:[]},
{type:"wilderness",name:"Will's Creek",x:470,y:1162,w:100,h:100,land:[99,37,131],river:[36],lakeshore:[]},
{type:"wilderness",name:"Winooski",x:1638,y:511,w:74,h:74,land:[121,126,127],river:[],lakeshore:[64,119]},
{type:"wilderness",name:"Wood Creek",x:1616,y:750,w:74,h:74,land:[128,73,106,126],river:[],lakeshore:[]},
{type:"wilderness",name:"Wyoming",x:1031,y:1005,w:74,h:74,land:[104,135,107],river:[66],lakeshore:[]},
{type:"wilderness",name:"Île-aux-Noix",x:1686,y:404,w:74,h:74,land:[127,42],river:[50],lakeshore:[116]},
{type:"mountain",name:"Adirondacks Central",x:1401,y:566,w:105,h:74,land:[122,54,112,121,106,72],river:[],lakeshore:[]},
{type:"mountain",name:"Adirondacks North",x:1450,y:462,w:105,h:74,land:[120,103,116,64],river:[],lakeshore:[]},
{type:"mountain",name:"Adirondacks South",x:1329,y:650,w:105,h:74,land:[120,89,72,19,56],river:[],lakeshore:[]},
{type:"mountain",name:"Allegheny Central",x:608,y:937,w:105,h:74,land:[55,130,99,75,62],river:[],lakeshore:[]},
{type:"mountain",name:"Allegheny North",x:644,y:793,w:105,h:74,land:[80,109,62,76],river:[],lakeshore:[]},
{type:"mountain",name:"Allegheny South",x:320,y:1279,w:105,h:74,land:[110,26,37,131,38],river:[],lakeshore:[]},
{type:"mountain",name:"Green Mountains Central",x:1695,y:610,w:105,h:74,land:[117,106,114,63,116,64],river:[],lakeshore:[]},
{type:"mountain",name:"Green Mountains North",x:1797,y:481,w:105,h:74,land:[53,63,116,119,82],river:[],lakeshore:[]},
{type:"mountain",name:"Green Mountains South",x:1573,y:841,w:105,h:74,land:[11,8,73,117,6],river:[],lakeshore:[]},
{type:"mountain",name:"Katskills",x:1241,y:965,w:105,h:74,land:[100,12,17,15,65,104,85],river:[],lakeshore:[]},
{type:"mountain",name:"Laurel Ridge North",x:484,y:1020,w:105,h:74,land:[71,88,77,123,99],river:[],lakeshore:[]},
{type:"mountain",name:"Laurel Ridge South",x:333,y:1159,w:105,h:74,land:[125,71,110,115],river:[],lakeshore:[]},
{type:"mountain",name:"Magnolia Hills",x:884,y:887,w:105,h:74,land:[60,107,66,113],river:[],lakeshore:[]},
{type:"mountain",name:"Notre Dame Mountains",x:1991,y:444,w:105,h:74,land:[53,82,134],river:[],lakeshore:[]},
{type:"mountain",name:"Notre Dame North",x:1987,y:316,w:105,h:74,land:[133,49,44,41],river:[],lakeshore:[]},
{type:"mountain",name:"Tuscarora Hills",x:967,y:1086,w:105,h:74,land:[118,29,66,101,33,35],river:[],lakeshore:[]},
{type:"mountain",name:"White Mountains Central",x:1864,y:737,w:105,h:74,land:[94,7,114,63],river:[],lakeshore:[]},
{type:"mountain",name:"White Mountains North",x:1994,y:611,w:105,h:74,land:[57,94,63,53],river:[],lakeshore:[]},
{type:"mountain",name:"White Mountains South",x:1731,y:895,w:105,h:74,land:[7,13,8,6],river:[],lakeshore:[]},
{type:"box",name:"Halifax",x:2331,y:515,w:163,h:130,land:[],river:[],lakeshore:[],is_fortress:true,is_port:true},
{type:"box",name:"Louisbourg",x:2331,y:309,w:163,h:131,land:[],river:[],lakeshore:[],is_fortress:true,is_port:true},
{type:"box",name:"Pays d'en Haut",x:318,y:335,w:128,h:193,land:[],river:[67,86,97,108],lakeshore:[]},
{type:"militia-box",name:"Northern Colonial Militias",x:1414,y:1390,w:197,h:72,land:[],river:[],lakeshore:[]},
{type:"militia-box",name:"Southern Colonial Militias",x:950,y:1521,w:197,h:72,land:[],river:[],lakeshore:[]},
{type:"militia-box",name:"St. Lawrence Canadian Militias",x:1838,y:69,w:224,h:73,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Abercromby",x:1839,y:1356,w:183,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Amherst",x:1684,y:1481,w:183,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Beaujeu",x:915,y:196,w:114,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Bougainville",x:1151,y:55,w:115,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Braddock",x:2346,y:1481,w:145,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Bradstreet",x:1876,y:1481,w:108,h:113,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Dieskau",x:915,y:55,w:114,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Drucour",x:1388,y:55,w:114,h:136,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Dumas",x:1033,y:196,w:114,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Dunbar",x:2384,y:1356,w:108,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Forbes",x:2111,y:1481,w:108,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Johnson",x:2031,y:1356,w:109,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Loudoun",x:1646,y:1356,w:184,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Lévis",x:1506,y:55,w:113,h:136,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Monckton",x:2148,y:1356,w:109,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Montcalm",x:1624,y:55,w:170,h:136,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Murray",x:1993,y:1481,w:109,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Rigaud",x:1152,y:196,w:114,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Shirley",x:2228,y:1481,w:109,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Vaudreuil",x:1270,y:55,w:113,h:137,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Villiers",x:1033,y:55,w:114,h:136,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Webb",x:2266,y:1356,w:108,h:112,land:[],river:[],lakeshore:[]},
{type:"leader-box",name:"Wolfe",x:1491,y:1481,w:183,h:112,land:[],river:[],lakeshore:[]}
]

if (typeof module !== 'undefined') module.exports = {cards,pieces,spaces}
